# TODO: add papers by configuration file
base_url: "https://arxiv.paperswithcode.com/api/v0/papers/"
user_name: "Ali Nikkhah"
repo_name: "arxic-daily"
show_authors: True
show_links: True
show_badge: True
max_results: 10

publish_readme: True
publish_gitpage: True
publish_wechat: False

# file paths
json_readme_path: './docs/cv-arxiv-daily.json'
json_gitpage_path: './docs/cv-arxiv-daily-web.json'
json_wechat_path: './docs/cv-arxiv-daily-wechat.json'

md_readme_path: 'README.md'
md_gitpage_path: './docs/index.md'
md_wechat_path: './docs/wechat.md'

# keywords to search
keywords:
    "Quantization": 
        filters: [
            "Quantization",
            "Post‑Training Quantization",
            "Static Quantization",
            "Dynamic Quantization",
            "Low‑bit Quantization",
            "Weight Quantization",
            "Adaptive Rounding",
            "Quantization‑Aware Training"
        ]
    "Pruning": 
        filters: [
            "Model Pruning",
            "Neural Network Pruning",
            "Weight Pruning",
            "Unstructured Pruning",
            "Structured Pruning",
            "Sparsification",
            "One‑shot Pruning"
        ]
    "Low‑Rank Factorization (SVD)": 
        filters: [
            "Low‑Rank Factorization",
            "Low‑Rank Approximation",
            "Singular Value Decomposition",
            "SVD",
            "Low‑Rank Matrix Decomposition",
            "Rank Reduction",
            "Low‑Rank Adaptation"
        ]
    "Reparameterization & Compression":
        filters: [
            "Reparameterization",
            "Low‑Rank Reparameterization",
            "Parameter‑Efficient Fine‑Tuning",
            "LoRA",
            "Manifold Reparameterization",
            "Neural Compression",
            "MCNC",
            "Non‑Linear Reparameterization"
        ]

